### ISSUE TITLE
"Hello Rust - RLTK Style!" fails to run on WSL, macOS

### ISSUE THREAD

**Issue by ssilva** [thebracket/rltk_rs#33]
**main.rs**:
```
use rltk::{Rltk, GameState, Console};

struct State {}
impl GameState for State {
    fn tick(&mut self, ctx : &mut Rltk) {
        ctx.cls();
        ctx.print(1, 1, "Hello Rust World");
    }
}

fn main() {
    let context = Rltk::init_simple8x8(80, 50, "Hello Rust World", "resources");
    let gs = State{ };
    rltk::main_loop(context, gs);
}
```

**Dependencies**:
```
[dependencies]
rltk = "0.5.12"
```

**Rust version**:
```
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/ssilva/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.39.0 (4560ea788 2019-11-04)
```

**Full backtrace**:
```
$ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: XOpenDisplayFailed', /home/ssilva/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha5/src/platform_impl/linux/mod.rs:561:9
stack backtrace:
   0:     0x7f46c36f95e4 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x7f46c36f95e4 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x7f46c36f95e4 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x7f46c36f95e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x7f46c371a50c - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x7f46c36f67d7 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x7f46c36fbb15 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x7f46c36fbb15 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7f46c36fbb15 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x7f46c36fb806 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x7f46c36fc215 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x7f46c341e488 - std::panicking::begin_panic::h984e4b60312952e1
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/panicking.rs:407
  12:     0x7f46c334c65a - winit::platform_impl::platform::EventLoop<T>::new_any_thread::h1b3b3225e6961cbd
                               at /home/ssilva/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha5/src/platform_impl/linux/mod.rs:561
  13:     0x7f46c334c0d1 - winit::platform_impl::platform::EventLoop<T>::new::hd5089acc5ced9d88
                               at /home/ssilva/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha5/src/platform_impl/linux/mod.rs:525
  14:     0x7f46c33477d1 - winit::event_loop::EventLoop<T>::with_user_event::h4a6f345aa2305156
                               at /home/ssilva/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha5/src/event_loop.rs:128
  15:     0x7f46c334779e - winit::event_loop::EventLoop<()>::new::h1df8502809ef4d38
                               at /home/ssilva/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha5/src/event_loop.rs:114
  16:     0x7f46c3110f1a - rltk::hal::native::init::init_raw::h07c03332143d80d4
                               at /home/ssilva/.cargo/registry/src/github.com-1ecc6299db9ec823/rltk-0.5.12/src/hal/native/init.rs:13
  17:     0x7f46c30e0385 - rltk::rltk::Rltk::init_raw::had9e4c5163e0dfff
                               at /home/ssilva/.cargo/registry/src/github.com-1ecc6299db9ec823/rltk-0.5.12/src/rltk.rs:42
  18:     0x7f46c30e0183 - rltk::rltk::Rltk::init_simple8x8::h37b239c4c43449c3
                               at /home/ssilva/.cargo/registry/src/github.com-1ecc6299db9ec823/rltk-0.5.12/src/rltk.rs:53
  19:     0x7f46c311c6fa - hellorust::main::heac78d8dc26c03eb
                               at src/main.rs:12
  20:     0x7f46c31202b0 - std::rt::lang_start::{{closure}}::ha3c8a83d83341202
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  21:     0x7f46c36fbc43 - std::rt::lang_start_internal::{{closure}}::ha04574f12d97cbe2
                               at src/libstd/rt.rs:49
  22:     0x7f46c36fbc43 - std::panicking::try::do_call::h7c2a8488f72db90c
                               at src/libstd/panicking.rs:292
  23:     0x7f46c36ffcaa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  24:     0x7f46c36fc70d - std::panicking::try::hc3a9b5da4250385d
                               at src/libstd/panicking.rs:271
  25:     0x7f46c36fc70d - std::panic::catch_unwind::hf27600bf8c37809a
                               at src/libstd/panic.rs:394
  26:     0x7f46c36fc70d - std::rt::lang_start_internal::h409d4f2fe51133b0
                               at src/libstd/rt.rs:48
  27:     0x7f46c3120289 - std::rt::lang_start::hd1ac00a4f0ae59d7
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  28:     0x7f46c311c76a - main
  29:     0x7f46c1fc1b97 - __libc_start_main
  30:     0x7f46c309dcfa - _start
  31:                0x0 - <unknown>
```
I'm guessing this has to do with a dependency being incompatible with the recently released Rust 1.40. However, I can't figure out from the backtrace which one is the culprit.

**Comment by ssilva** [comment]
Fixed with `rltk = "0.5.13"`.
